repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=1500']
  - id: check-toml
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.18
  hooks:
    - id: ruff-check
      args: [--fix, --exit-non-zero-on-fix]
      types: [ python ]
    - id: ruff-format
      types: [ python ]
      exclude: ^docs/source/gallery/

- repo: https://github.com/MarcoGorelli/madforhooks
  rev: 0.4.1
  hooks:
    - id: no-print-statements

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
      exclude: ^docs/source/gallery/
