"""None plotting backend."""
from .core import (
    ciliney,
    create_plotting_grid,
    fill_between_y,
    get_background_color,
    get_default_aes,
    grid,
    hist,
    hline,
    hspan,
    line,
    multiple_lines,
    remove_axis,
    remove_ticks,
    savefig,
    scale_fig_size,
    scatter,
    set_figure_title,
    set_ticklabel_visibility,
    set_y_scale,
    show,
    step,
    text,
    ticklabel_props,
    title,
    vline,
    vspan,
    xlabel,
    xlim,
    xticks,
    ylabel,
    ylim,
    yticks,
)
from .legend import legend
