"""
# Linear model plot

Posterior predictive and mean plots for regression-like data. The `plot_lm` function
visualizes credible intervals around predictions alongside observed data points. It
expects three groups in the input DataTree: `constant_data` for the independent variable
(x-axis), `observed_data` for the response variable, and a group with predicted values.
The `group` parameter controls which group is used for the predictions and defaults to
`posterior_predictive`. Other valid options are `posterior`, `prior`, `prior_predictive`,
and `predictions`.

The main visual elements are:

- **pe_line**: Line for the mean, median, or mode of the predictions E(y|x), or of the
  linear predictor E(η|x).
- **ci_band**: Filled credible interval band for E(y|x) or E(η|x).
- **ci_vlines**: Vertical credible interval lines, intended for categorical or discrete x
  variables where `ci_band` or `ci_bounds` do not work well.
- **ci_bounds**: Lines for the upper and lower bounds of a credible interval, similar to
  `ci_band` but using lines instead of a filled area. Disabled by default.
- **observed_scatter**: Scatter of observed data points.

This example uses synthetic data from a simple linear regression model
y = 2 + 0.5 * x + ε, where ε ~ Normal(0, 0.5). The posterior predictive
samples are generated by adding the same Gaussian noise to the true regression
line. By default, `plot_lm` applies Savitzky-Golay smoothing (`smooth=True`)
and shows a filled credible interval band (`ci_band`) together with a point
estimate line (`pe_line`) and observed data scatter (`observed_scatter`).
`ci_vlines` and `ci_bounds` are disabled by default.

---

:::{seealso}
API Documentation: {func}`~arviz_plots.plot_lm`

Old ArviZ `plot_lm` [documentation](https://python.arviz.org/en/v0.23.0/api/generated/arviz.plot_lm.html)
:::
"""
import numpy as np
from arviz_base import from_dict

import arviz_plots as azp

azp.style.use("arviz-variat")

np.random.seed(42)
x_data = np.random.normal(0, 1, 100)
y_data = 2 + x_data * 0.5 + np.random.normal(0, 0.5, 100)
y_data_rep = np.random.normal(2 + x_data * 0.5, 0.5, (4, 200, 100))

dt = from_dict(
    {
        "posterior_predictive": {"y": y_data_rep},
        "observed_data": {"y": y_data},
        "constant_data": {"x": x_data},
    },
    dims={"y": ["obs_id"], "x": ["obs_id"]},
    coords={"obs_id": range(100)},
)

pc = azp.plot_lm(
    dt,
    backend="none",  # change to preferred backend
)
pc.show()
