# File generated with docstub

import plotly.graph_objects as go
from _typeshed import Incomplete

axis_common: Incomplete
h_template: Incomplete

arviz_cetrino_template: Incomplete
arviz_cetrino_template: Incomplete
data: Incomplete
scatter: Incomplete
arviz_cetrino_template: Incomplete
data: Incomplete
bar: Incomplete
arviz_cetrino_template: Incomplete
layout: Incomplete
paper_bgcolor: Incomplete
arviz_cetrino_template: Incomplete
layout: Incomplete
plot_bgcolor: Incomplete
arviz_cetrino_template: Incomplete
layout: Incomplete
polar: Incomplete
bgcolor: Incomplete
arviz_cetrino_template: Incomplete
layout: Incomplete
ternary: Incomplete
bgcolor: Incomplete
arviz_cetrino_template: Incomplete
layout: Incomplete
margin: Incomplete
arviz_cetrino_template: Incomplete
layout: Incomplete
xaxis: Incomplete
arviz_cetrino_template: Incomplete
layout: Incomplete
yaxis: Incomplete
arviz_cetrino_template: Incomplete
layout: Incomplete
colorway: Incomplete

arviz_tenui_template: Incomplete
arviz_tenui_template: Incomplete
data: Incomplete
scatter: Incomplete
arviz_tenui_template: Incomplete
data: Incomplete
bar: Incomplete
arviz_tenui_template: Incomplete
layout: Incomplete
paper_bgcolor: Incomplete
arviz_tenui_template: Incomplete
layout: Incomplete
plot_bgcolor: Incomplete
arviz_tenui_template: Incomplete
layout: Incomplete
polar: Incomplete
bgcolor: Incomplete
arviz_tenui_template: Incomplete
layout: Incomplete
ternary: Incomplete
bgcolor: Incomplete
arviz_tenui_template: Incomplete
layout: Incomplete
margin: Incomplete
arviz_tenui_template: Incomplete
layout: Incomplete
xaxis: Incomplete
arviz_tenui_template: Incomplete
layout: Incomplete
yaxis: Incomplete
arviz_tenui_template: Incomplete
layout: Incomplete
colorway: Incomplete

arviz_variat_template: Incomplete
arviz_variat_template: Incomplete
data: Incomplete
scatter: Incomplete
arviz_variat_template: Incomplete
data: Incomplete
bar: Incomplete
arviz_variat_template: Incomplete
layout: Incomplete
paper_bgcolor: Incomplete
arviz_variat_template: Incomplete
layout: Incomplete
plot_bgcolor: Incomplete
arviz_variat_template: Incomplete
layout: Incomplete
polar: Incomplete
bgcolor: Incomplete
arviz_variat_template: Incomplete
layout: Incomplete
ternary: Incomplete
bgcolor: Incomplete
arviz_variat_template: Incomplete
layout: Incomplete
margin: Incomplete
arviz_variat_template: Incomplete
layout: Incomplete
xaxis: Incomplete
arviz_variat_template: Incomplete
layout: Incomplete
yaxis: Incomplete
arviz_variat_template: Incomplete
layout: Incomplete
colorway: Incomplete

arviz_vibrant_template: Incomplete
arviz_vibrant_template: Incomplete
data: Incomplete
scatter: Incomplete
arviz_vibrant_template: Incomplete
data: Incomplete
bar: Incomplete
arviz_vibrant_template: Incomplete
layout: Incomplete
paper_bgcolor: Incomplete
arviz_vibrant_template: Incomplete
layout: Incomplete
plot_bgcolor: Incomplete
arviz_vibrant_template: Incomplete
layout: Incomplete
polar: Incomplete
bgcolor: Incomplete
arviz_vibrant_template: Incomplete
layout: Incomplete
ternary: Incomplete
bgcolor: Incomplete
arviz_vibrant_template: Incomplete
layout: Incomplete
margin: Incomplete
arviz_vibrant_template: Incomplete
layout: Incomplete
xaxis: Incomplete
arviz_vibrant_template: Incomplete
layout: Incomplete
yaxis: Incomplete
arviz_vibrant_template: Incomplete
layout: Incomplete
colorway: Incomplete

axis_darkgrid: Incomplete
arviz_darkgrid_template: Incomplete
arviz_darkgrid_template: Incomplete
data: Incomplete
scatter: Incomplete
arviz_darkgrid_template: Incomplete
data: Incomplete
bar: Incomplete
arviz_darkgrid_template: Incomplete
layout: Incomplete
paper_bgcolor: Incomplete
arviz_darkgrid_template: Incomplete
layout: Incomplete
plot_bgcolor: Incomplete
arviz_darkgrid_template: Incomplete
layout: Incomplete
polar: Incomplete
bgcolor: Incomplete
arviz_darkgrid_template: Incomplete
layout: Incomplete
ternary: Incomplete
bgcolor: Incomplete
arviz_darkgrid_template: Incomplete
layout: Incomplete
margin: Incomplete
arviz_darkgrid_template: Incomplete
layout: Incomplete
xaxis: Incomplete
arviz_darkgrid_template: Incomplete
layout: Incomplete
yaxis: Incomplete
arviz_darkgrid_template: Incomplete
layout: Incomplete
colorway: Incomplete

axis_tumma: Incomplete
arviz_tumma_template: Incomplete
arviz_tumma_template: Incomplete
data: Incomplete
scatter: Incomplete
arviz_tumma_template: Incomplete
data: Incomplete
bar: Incomplete
arviz_tumma_template: Incomplete
layout: Incomplete
paper_bgcolor: Incomplete
arviz_tumma_template: Incomplete
layout: Incomplete
plot_bgcolor: Incomplete
arviz_tumma_template: Incomplete
layout: Incomplete
polar: Incomplete
bgcolor: Incomplete
arviz_tumma_template: Incomplete
layout: Incomplete
ternary: Incomplete
bgcolor: Incomplete
arviz_tumma_template: Incomplete
layout: Incomplete
font: Incomplete
color: Incomplete
arviz_tumma_template: Incomplete
layout: Incomplete
title: Incomplete
font: Incomplete
color: Incomplete
arviz_tumma_template: Incomplete
layout: Incomplete
margin: Incomplete
arviz_tumma_template: Incomplete
layout: Incomplete
xaxis: Incomplete
arviz_tumma_template: Incomplete
layout: Incomplete
yaxis: Incomplete
arviz_tumma_template: Incomplete
layout: Incomplete
legend: Incomplete
bgcolor: Incomplete
arviz_tumma_template: Incomplete
layout: Incomplete
colorway: Incomplete
